NYT-674: support auth
tractoai/testcontainers-ytsaurus pull request #8
Opened 2024-10-10 11:13 UTC by dmi-feo

2024-10-14 17:50 UTC, dmi-feo commented
DO NOT MERGE until we figure out what the heck is going on with yt images

2024-10-15 07:22 UTC, l0kix2 requested changes

2024-10-15 07:22 UTC, l0kix2 commented on ytsaurus.go
> +// WithAuth enables authentication on http proxies and creates `admin` user with password and token `password`.
Maybe we could provide constants for password/token here in lib so we don't have to hardcode them in the user code.

2024-10-15 07:22 UTC, l0kix2 commented on ytsaurus_test.go
> +
hm, linter doesn't catch unsorted imports 🤔

2024-10-16 11:17 UTC, dmi-feo commented on ytsaurus_test.go
> +
It seems that goimports is happy with this sorting, which is strange

2024-10-16 11:22 UTC, dmi-feo commented
The fail of the test is expected since `stable` version of yt image has been rolled back

2024-10-16 11:36 UTC, l0kix2 commented
> The fail of the test is expected since `stable` version of yt image has been rolled back

You mean ytlocal stable? As far as i saw issue was localized. Will it be back or we better use some nightly ytlocal version here?

2024-10-16 12:41 UTC, dmi-feo commented
> As far as i saw issue was localized.

Probably. They say they got something related to ipv4/ipv6, but I don't know what exactly it is. However, stable image is still too old for this rock'n'roll.

> we better use some nightly ytlocal version here?

That's a nice idea since only nightly builds have versioning :)

2024-10-16 14:28 UTC, l0kix2 approved these changes

2024-10-16 14:29 UTC, l0kix2 commented
Great, thanks!

2024-10-16 14:29 UTC, merged

2024-10-16 14:29 UTC, dmi-feo commented
So, we can either
- merge it with the nightly image
- or wait for stable release update

The first approach has its own advantages (all users of this lib will use the same image) and disadvantages (we can't be sure everything works fine in this nightly buid)

2024-10-16 14:29 UTC, dmi-feo commented
Oh, it's merged)